### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by Kylogias** [jdah/jdh-8#1]
On windows, using make that comes with mingw-w64 (i think), the compilation fails with error **'unistd.h' file not found**

Windows 10
make version 4.3
Clang version 11.0.0

EDIT :: Apparently my clang toolchain was incorrect, but now I'm missing poll.h instead of unistd.h

**Comment by youngchief-btw** [comment]
It's a missing header, are you sure you installed everything you need?

**Comment by Kylogias** [comment]
> It's a missing header, are you sure you installed everything you need?

I searched it up, and it's for accessing POSIX os procedures

**Comment by youngchief-btw** [comment]
I feel like it's because since Windows it's exactly POSIX compliant. 
Does MinGW have a POSIX compatibility layer?

**Comment by Kylogias** [comment]
Using the MSYS2 version of clang worked, but now I'm getting a 404 for poll.h

**Comment by jdah** [comment]
This requires complete POSIX compliance from the host system, sorry. Will add the info into. the README.

**Comment by Kylogias** [comment]
> This requires complete POSIX compliance from the host system, sorry. Will add the info into. the README.

Can you give me a list of POSIX functions used so I can _**TRY**_ to make it compatible with windows?

**Comment by rupansh** [comment]
> > This requires complete POSIX compliance from the host system, sorry. Will add the info into. the README.
> 
> Can you give me a list of POSIX functions used so I can _**TRY**_ to make it compatible with windows?

Nuke the posix header see errors.

**Comment by youngchief-btw** [comment]
There's already POSIX compatibility layers for Windows. Just look online for the one that suits you.

**Comment by youngchief-btw** [comment]
Can I write Windows specific instructions on the README?

**Comment by KingUndeadCodes** [comment]
You should fork the repository and edit it that way. If our lord and savior jdh likes your contribution he may push it.

**Comment by jdah** [comment]
> Can I write Windows specific instructions on the README?

Feel free to make a PR if you can get this compiling on Windows. Good luck though since the emulator uses `readline` which is very POSIX-specific, among other things. The test runner also relies a lot on POSIX functions (`mktemp`, `opendir`, etc.).

**Comment by Kylogias** [comment]
I'm trying to make a Windows "compatibility patch". Is the history feature in Readline ever used outside of adding things to history? If so, where

**Comment by Kylogias** [comment]
I GOT THE EMULATOR TO COMPILE!!! Halfway done (I might not compile the tests, although I will have to look at them first)

**Comment by Kylogias** [comment]
The full thing compiled (even the tests). The emulator was the hardest to compile, I had to make some compatibility code. There was only 1 error in the assembler which I don't think was POSIX specific. The tests compiled first try, no error correction necessary

**Comment by jdah** [comment]
Fixed with merge of cd6cf42a3e0e333939255c5fdbc5202d122e727e.
