### ISSUE TITLE
Hello Jdh

### ISSUE THREAD

**Issue by ak8749** [jdah/jdh-8#13]
Hello jdh. You're the best youtuber and you are so smart. I cant express how much i love watching your videos. You are a genius. You are so INTELLIGENT. Please reply to this. this is the only place where i can talk to you. Dude i just want to say that you should keep doing this stuff, its really nice!!! I respect you, and your programming skills. I have so many questions but i dont know where to talk to you. Please man, you are literally the most impressive programmer i have seen. Thank you so so much for all of these videos. I will support you throughout your youtube life. 

Thank you

**Comment by jdah** [comment]
Hey, thanks! If you want to contact me, my e-mail is in my GitHub profile and on my YouTube at jdh<at>jdh.gg. GitHub issues isn't quite the right place for this...

**Comment by ak8749** [comment]
OMG holy dude its you. its you. dude i emailed you please respond you're the best!!!

**Comment by nikeedev** [comment]
> OMG holy dude its you. its you. dude i emailed you please respond you're the best!!!

you don't need to overreact, but i agree with the part that he is genius. @jdah you are indeed a creative guy. BTW, i sent you mail, thanks if you can answer it! :)

**Comment by TheCodingEgg** [comment]
@jdah what ide do you use

**Comment by nikeedev** [comment]
> @jdah what ide do you use

Neovim, you can see it on most of his streams.

https://github.com/jdah/dotfiles/tree/master/.config/nvim
