### ISSUE TITLE
How to print

### ISSUE THREAD

**Issue by atmeh** [jdah/jdh-8#14]
How am I supposed to print strings or numbers with the assembly? Do I have to print to the screen or is there a method to print without using the screen module and just printing in the emulator?

**Comment by Kylogias** [comment]
There is no way to communicate to the emulator "Hey, I want to print <TEXT> to the console", at least not out of the box. However, you can make a device which handles console IO and use OUTB with that device. Alternatively, you can make a font with code and use the screen device. I'm not sure if you can add devices/modules outside of hardcoding inside of the executable

**Comment by jdah** [comment]
@Kylogias is correct, please take a look at `programs/pong.asm` to see how to print to screen.
