### ISSUE TITLE
What text editor do you use?

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [jdah/jdh-8#23]
hi jdh or whoever answers this,

does anybody know what text editor he uses?

thanks
and remember to subscribe to jdh because **yes**

**Comment by jdah** [comment]
Hey, this isn't the right place this (please don't use GitHub issues this way, I have an e-mail on my channel). but I use NeoVim. Says so in all my video descriptions.

**Comment by TheAwesomeGuy47** [comment]
oh im sorry :(
