### ISSUE TITLE
Just a hint.. What about using am2901 instead of 74181?

### ISSUE THREAD

**Issue by roman65536** [jdah/jdh-8#28]
Really impressing! But instead using 74181 as an option, I suggest am2901. All you need is in it. 8 registers (dual port ram), alu, shift etc. Browse old amd stuff on bitsavers.org

Rgds
Roman

**Comment by jdah** [comment]
Thanks for the suggestion, would probably consider it with a redesign :-)

**Comment by ellisgl** [comment]
I was thinking about that myself, since it would replace some other stuff, not just the ALU.
Of course I haven't found a am2901 Logisim .circ file yet (I lost one I made a while back ago).
