### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by hdfsyu** [jdah/jdh-8#29]
I know this might sound like I am a noob (which I am) but I don't know how to use emu and this is what is popping out: [hdfsyu@archlinux bin]$ ./emu -l test
Assertion failed. (emu/emu.c:273)
Help please

**Comment by jdah** [comment]
Sorry the documentation isn't super clear, but you need to give an address to load the ROM at. So `$ ./emu -l test 0` will work just fine :-)
