### ISSUE TITLE
Make doesn't work on first run

### ISSUE THREAD

**Issue by rmccampbell** [jdah/jdh-8#30]
The "asm" make command depends on the generated builtin_macros.c, which isn't listed in the ASM_OBJ on the first run. This causes make to generate a linker error. When run a second time builtin_macros.c is collected in ASM_SRC and ASM_OBJ which causes it to build successfully.

**Comment by jdah** [comment]
Fixed in 77507880c57f5f966ba6d9c6a612097910e0dcad :)
