### ISSUE TITLE
Error when running ROM

### ISSUE THREAD

**Issue by hdfsyu** [jdah/jdh-8#31]
When I run the rom (I tried using ./emu -l test 0) and then I typed run and it just gave me a bunch of errors... then I tried ./emu -l test 3 then typed run 3 and it worked but now it says "Press enter to stop simulation" and it does nothing

**Comment by jdah** [comment]
Please read the README, it says that `emu` will load the specified binary at the given address. You can either set the `PC` manually to that address with `SET` or you can just load it at `0`. The `RUN` command is `RUN <hertz?>`, the second argument is not an address.

Please read the README.
