### ISSUE TITLE
Libraries required for Logisim.

### ISSUE THREAD

**Issue by arastaskiran** [jdah/jdh-8#35]
Logisim schematic has some library dependencies. Can you share these libraries as well

![Screenshot from 2021-12-29 21-35-22](https://user-images.githubusercontent.com/29253596/147693287-8837c51b-c585-4a14-be4c-a88237732c8e.png)
?

**Comment by arastaskiran** [comment]
Missing Library List:

jdh8:
component '74151' missing from library '6' [video74.74151((1080,1130))]
component '74573' missing from library '6' [video74.74573((1080,1330))]
component '74279' missing from library '6' [video74.74279((1080,720))]
component '74279' missing from library '6' [video74.74279((1080,930))]
component '74688' missing from library '6' [video74.74688((410,1380))]
component '74682' missing from library '6' [video74.74682((410,1610))]
component '74682' missing from library '6' [video74.74682((410,1830))]
component '74688' missing from library '6' [video74.74688((410,2050))]
component '74688' missing from library '6' [video74.74688((410,2270))]
component '74688' missing from library '6' [video74.74688((410,2490))]
component '74688' missing from library '6' [video74.74688((720,1060))]
component '74688' missing from library '6' [video74.74688((720,1310))]
component '74688' missing from library '6' [video74.74688((720,1610))]
component '74688' missing from library '6' [video74.74688((720,310))]
component '74688' missing from library '6' [video74.74688((720,560))]
component '74688' missing from library '6' [video74.74688((720,810))]
component '74244' missing from library '6' [alu74.74244((1200,1080))]
component '74244' missing from library '6' [alu74.74244((1200,1320))]
component '74244' missing from library '6' [alu74.74244((1200,190))]
component '74244' missing from library '6' [alu74.74244((1200,420))]
component '74244' missing from library '6' [alu74.74244((1420,1320))]
component '74244' missing from library '6' [alu74.74244((1640,1330))]
component '74244' missing from library '6' [alu74.74244((700,1200))]
component '74374' missing from library '6' [alu74.74374((700,180))]
component '74374' missing from library '6' [alu74.74374((700,420))]
component '74138' missing from library '6' [alu74.74138((960,980))]
component '74573' missing from library '6' [regs74.74573((1060,1070))]
component '74238' missing from library '6' [regs74.74238((1060,140))]
component '74573' missing from library '6' [regs74.74573((1060,340))]
component '74573' missing from library '6' [regs74.74573((1060,580))]
component '74573' missing from library '6' [regs74.74573((1060,820))]
component '74138' missing from library '6' [regs74.74138((1270,140))]
component '74573' missing from library '6' [regs74.74573((1270,340))]
component '74573' missing from library '6' [regs74.74573((1270,580))]
component '74573' missing from library '6' [regs74.74573((1270,820))]
component '74573' missing from library '6' [regs74.74573((830,1060))]
component '74573' missing from library '6' [regs74.74573((830,340))]
component '74573' missing from library '6' [regs74.74573((830,580))]
component '74573' missing from library '6' [regs74.74573((830,820))]
component '74573' missing from library '6' [opc74.74573((600,1110))]
component '74573' missing from library '6' [opc74.74573((600,150))]
component '74573' missing from library '6' [opc74.74573((600,390))]
component '74573' missing from library '6' [opc74.74573((600,630))]
component '74573' missing from library '6' [opc74.74573((600,870))]
component '74238' missing from library '6' [opc74.74238((850,670))]
component '74238' missing from library '6' [main_test.74238((1280,420))]
component '74688' missing from library '6' [auxregs74.74688((1100,300))]
component '74193' missing from library '6' [auxregs74.74193((1100,520))]
component '74193' missing from library '6' [auxregs74.74193((1100,720))]
component '74244' missing from library '6' [auxregs74.74244((1100,80))]
component '74244' missing from library '6' [auxregs74.74244((1100,920))]
component '74573' missing from library '6' [auxregs74.74573((1360,300))]
component '74193' missing from library '6' [auxregs74.74193((1360,520))]
component '74193' missing from library '6' [auxregs74.74193((1360,720))]
component '74244' missing from library '6' [auxregs74.74244((1360,80))]
component '74244' missing from library '6' [auxregs74.74244((1360,920))]
component '74573' missing from library '6' [auxregs74.74573((1570,300))]
component '74138' missing from library '6' [auxregs74.74138((550,960))]
component '74193' missing from library '6' [auxregs74.74193((560,320))]
component '74193' missing from library '6' [auxregs74.74193((560,520))]
component '74244' missing from library '6' [auxregs74.74244((560,720))]
component '74244' missing from library '6' [auxregs74.74244((560,80))]
component '74193' missing from library '6' [auxregs74.74193((820,320))]
component '74193' missing from library '6' [auxregs74.74193((820,520))]
component '74244' missing from library '6' [auxregs74.74244((820,720))]
component '74244' missing from library '6' [auxregs74.74244((820,80))]
component '74138' missing from library '6' [auxregs74.74138((820,960))]
component '74573' missing from library '6' [addr74.74573((440,310))]
component '74573' missing from library '6' [addr74.74573((440,550))]
component '74573' missing from library '6' [addr74.74573((440,60))]
component '74573' missing from library '6' [addr74.74573((440,800))]
component '74573' missing from library '6' [addr74.74573((680,310))]
component '74573' missing from library '6' [addr74.74573((680,550))]
component '74573' missing from library '6' [addr74.74573((680,60))]
component '74573' missing from library '6' [addr74.74573((680,800))]
component '74573' missing from library '6' [control74.74573((680,320))]
component '74573' missing from library '6' [control74.74573((680,80))]
component '74573' missing from library '6' [dev74.74573((630,310))]
component '74573' missing from library '6' [dev74.74573((630,70))]
component '74573' missing from library '6' [dev74.74573((820,70))]
component '74573' missing from library '6' [vram74.74573((600,100))]
component '74573' missing from library '6' [vram74.74573((600,340))]
component '74573' missing from library '6' [vram74.74573((600,580))]
component '74573' missing from library '6' [vram74.74573((600,820))]
component '74573' missing from library '6' [vram74.74573((920,790))]
component '74151' missing from library '6' [main74.74151((1040,1130))]
component '74573' missing from library '6' [main74.74573((1040,1330))]
component '74573' missing from library '6' [main74.74573((1040,1610))]
component '74573' missing from library '6' [main74.74573((1040,1850))]
component '74573' missing from library '6' [main74.74573((1040,2090))]
component '74573' missing from library '6' [main74.74573((1040,2330))]
component '74573' missing from library '6' [main74.74573((1040,2920))]
component '74573' missing from library '6' [main74.74573((1040,3160))]
component '74573' missing from library '6' [main74.74573((1040,3400))]
component '74573' missing from library '6' [main74.74573((1040,3640))]
component '74573' missing from library '6' [main74.74573((1040,3880))]
component '74279' missing from library '6' [main74.74279((1040,720))]
component '74279' missing from library '6' [main74.74279((1040,930))]
component '74682' missing from library '6' [main74.74682((1380,1770))]
component '74573' missing from library '6' [main74.74573((1380,1990))]
component '74244' missing from library '6' [main74.74244((1380,2210))]
component '74244' missing from library '6' [main74.74244((1380,2920))]
component '74573' missing from library '6' [main74.74573((1380,3150))]
component '74573' missing from library '6' [main74.74573((1380,3380))]
component '74573' missing from library '6' [main74.74573((1380,3610))]
component '74573' missing from library '6' [main74.74573((1720,1610))]
component '74573' missing from library '6' [main74.74573((1720,1830))]
component '74573' missing from library '6' [main74.74573((1720,2050))]
component '74573' missing from library '6' [main74.74573((1720,2270))]
component '74573' missing from library '6' [main74.74573((1720,2500))]
component '74138' missing from library '6' [main74.74138((1720,2720))]
component '74573' missing from library '6' [main74.74573((1720,2920))]
component '74244' missing from library '6' [main74.74244((2060,1150))]
component '74244' missing from library '6' [main74.74244((2060,1380))]
component '74573' missing from library '6' [main74.74573((2060,1620))]
component '74573' missing from library '6' [main74.74573((2060,1840))]
component '74573' missing from library '6' [main74.74573((2060,2060))]
component '74573' missing from library '6' [main74.74573((2060,2280))]
component '74573' missing from library '6' [main74.74573((2060,2500))]
component '74138' missing from library '6' [main74.74138((2060,2710))]
component '74374' missing from library '6' [main74.74374((2060,2920))]
component '74374' missing from library '6' [main74.74374((2060,3160))]
component '74244' missing from library '6' [main74.74244((2060,3940))]
component '74573' missing from library '6' [main74.74573((2060,600))]
component '74573' missing from library '6' [main74.74573((2400,1100))]
component '74573' missing from library '6' [main74.74573((2400,1340))]
component '74244' missing from library '6' [main74.74244((2400,1610))]
component '74244' missing from library '6' [main74.74244((2400,1830))]
component '74244' missing from library '6' [main74.74244((2400,2060))]
component '74193' missing from library '6' [main74.74193((2400,2280))]
component '74193' missing from library '6' [main74.74193((2400,2480))]
component '74244' missing from library '6' [main74.74244((2400,2670))]
component '74138' missing from library '6' [main74.74138((2400,3720))]
component '74573' missing from library '6' [main74.74573((2400,620))]
component '74573' missing from library '6' [main74.74573((2400,860))]
component '74573' missing from library '6' [main74.74573((2740,1100))]
component '74573' missing from library '6' [main74.74573((2740,1340))]
component '74244' missing from library '6' [main74.74244((2740,1600))]
component '74244' missing from library '6' [main74.74244((2740,1830))]
component '74244' missing from library '6' [main74.74244((2740,2060))]
component '74193' missing from library '6' [main74.74193((2740,2280))]
component '74193' missing from library '6' [main74.74193((2740,2480))]
component '74244' missing from library '6' [main74.74244((2740,2670))]
component '74244' missing from library '6' [main74.74244((2740,2910))]
component '74244' missing from library '6' [main74.74244((2740,3140))]
component '74244' missing from library '6' [main74.74244((2740,3750))]
component '74244' missing from library '6' [main74.74244((2740,3980))]
component '74573' missing from library '6' [main74.74573((2740,860))]
component '74573' missing from library '6' [main74.74573((3080,1140))]
component '74573' missing from library '6' [main74.74573((3080,1370))]
component '74193' missing from library '6' [main74.74193((3080,2270))]
component '74193' missing from library '6' [main74.74193((3080,2470))]
component '74244' missing from library '6' [main74.74244((3080,2670))]
component '74244' missing from library '6' [main74.74244((3080,3970))]
component '74573' missing from library '6' [main74.74573((3080,680))]
component '74573' missing from library '6' [main74.74573((3080,910))]
component '74244' missing from library '6' [main74.74244((3410,3970))]
component '74688' missing from library '6' [main74.74688((3420,2050))]
component '74193' missing from library '6' [main74.74193((3420,2270))]
component '74193' missing from library '6' [main74.74193((3420,2470))]
component '74244' missing from library '6' [main74.74244((3420,2670))]
component '74138' missing from library '6' [main74.74138((3420,310))]
component '74238' missing from library '6' [main74.74238((3420,500))]
component '74573' missing from library '6' [main74.74573((3420,690))]
component '74688' missing from library '6' [main74.74688((360,1380))]
component '74682' missing from library '6' [main74.74682((360,1610))]
component '74682' missing from library '6' [main74.74682((360,1830))]
component '74688' missing from library '6' [main74.74688((360,2050))]
component '74688' missing from library '6' [main74.74688((360,2270))]
component '74688' missing from library '6' [main74.74688((360,2490))]
component '74238' missing from library '6' [main74.74238((360,3450))]
component '74238' missing from library '6' [main74.74238((4070,550))]
component '74688' missing from library '6' [main74.74688((700,1060))]
component '74688' missing from library '6' [main74.74688((700,1310))]
component '74688' missing from library '6' [main74.74688((700,1610))]
component '74688' missing from library '6' [main74.74688((700,310))]
component '74688' missing from library '6' [main74.74688((700,560))]
component '74688' missing from library '6' [main74.74688((700,810))]
component '74151' missing from library '6' [pretty74.74151((1040,1130))]
component '74573' missing from library '6' [pretty74.74573((1040,1330))]
component '74573' missing from library '6' [pretty74.74573((1040,1610))]
component '74573' missing from library '6' [pretty74.74573((1040,1850))]
component '74573' missing from library '6' [pretty74.74573((1040,2090))]
component '74573' missing from library '6' [pretty74.74573((1040,2330))]
component '74573' missing from library '6' [pretty74.74573((1040,2920))]
component '74573' missing from library '6' [pretty74.74573((1040,3160))]
component '74573' missing from library '6' [pretty74.74573((1040,3400))]
component '74573' missing from library '6' [pretty74.74573((1040,3640))]
component '74573' missing from library '6' [pretty74.74573((1040,3880))]
component '74279' missing from library '6' [pretty74.74279((1040,720))]
component '74279' missing from library '6' [pretty74.74279((1040,930))]
component '74573' missing from library '6' [pretty74.74573((1380,2100))]
component '74244' missing from library '6' [pretty74.74244((1380,2320))]
component '74244' missing from library '6' [pretty74.74244((1380,2920))]
component '74573' missing from library '6' [pretty74.74573((1380,3150))]
component '74573' missing from library '6' [pretty74.74573((1380,3380))]
component '74573' missing from library '6' [pretty74.74573((1380,3610))]
component '74688' missing from library '6' [pretty74.74688((1380,3830))]
component '74573' missing from library '6' [pretty74.74573((1720,1610))]
component '74573' missing from library '6' [pretty74.74573((1720,1830))]
component '74573' missing from library '6' [pretty74.74573((1720,2050))]
component '74573' missing from library '6' [pretty74.74573((1720,2270))]
component '74573' missing from library '6' [pretty74.74573((1720,2500))]
component '74138' missing from library '6' [pretty74.74138((1720,2720))]
component '74244' missing from library '6' [pretty74.74244((2060,1150))]
component '74244' missing from library '6' [pretty74.74244((2060,1380))]
component '74573' missing from library '6' [pretty74.74573((2060,1620))]
component '74573' missing from library '6' [pretty74.74573((2060,1840))]
component '74573' missing from library '6' [pretty74.74573((2060,2060))]
component '74573' missing from library '6' [pretty74.74573((2060,2280))]
component '74573' missing from library '6' [pretty74.74573((2060,2500))]
component '74138' missing from library '6' [pretty74.74138((2060,2710))]
component '74374' missing from library '6' [pretty74.74374((2060,2920))]
component '74374' missing from library '6' [pretty74.74374((2060,3160))]
component '74244' missing from library '6' [pretty74.74244((2060,3940))]
component '74573' missing from library '6' [pretty74.74573((2060,600))]
component '74573' missing from library '6' [pretty74.74573((2400,1100))]
component '74573' missing from library '6' [pretty74.74573((2400,1340))]
component '74244' missing from library '6' [pretty74.74244((2400,1610))]
component '74244' missing from library '6' [pretty74.74244((2400,1830))]
component '74244' missing from library '6' [pretty74.74244((2400,2060))]
component '74193' missing from library '6' [pretty74.74193((2400,2280))]
component '74193' missing from library '6' [pretty74.74193((2400,2480))]
component '74244' missing from library '6' [pretty74.74244((2400,2670))]
component '74138' missing from library '6' [pretty74.74138((2400,3720))]
component '74244' missing from library '6' [pretty74.74244((2400,3940))]
component '74573' missing from library '6' [pretty74.74573((2400,620))]
component '74573' missing from library '6' [pretty74.74573((2400,860))]
component '74573' missing from library '6' [pretty74.74573((2740,1100))]
component '74573' missing from library '6' [pretty74.74573((2740,1340))]
component '74244' missing from library '6' [pretty74.74244((2740,1600))]
component '74244' missing from library '6' [pretty74.74244((2740,1830))]
component '74244' missing from library '6' [pretty74.74244((2740,2060))]
component '74193' missing from library '6' [pretty74.74193((2740,2280))]
component '74193' missing from library '6' [pretty74.74193((2740,2480))]
component '74244' missing from library '6' [pretty74.74244((2740,2670))]
component '74244' missing from library '6' [pretty74.74244((2740,2910))]
component '74244' missing from library '6' [pretty74.74244((2740,3140))]
component '74244' missing from library '6' [pretty74.74244((2740,3750))]
component '74244' missing from library '6' [pretty74.74244((2740,3980))]
component '74573' missing from library '6' [pretty74.74573((2740,860))]
component '74573' missing from library '6' [pretty74.74573((3080,1140))]
component '74573' missing from library '6' [pretty74.74573((3080,1370))]
component '74193' missing from library '6' [pretty74.74193((3080,2270))]
component '74193' missing from library '6' [pretty74.74193((3080,2470))]
component '74244' missing from library '6' [pretty74.74244((3080,2670))]
component '74244' missing from library '6' [pretty74.74244((3080,3970))]
component '74573' missing from library '6' [pretty74.74573((3080,680))]
component '74573' missing from library '6' [pretty74.74573((3080,910))]
component '74244' missing from library '6' [pretty74.74244((3410,3970))]
component '74688' missing from library '6' [pretty74.74688((3420,2050))]
component '74193' missing from library '6' [pretty74.74193((3420,2270))]
component '74193' missing from library '6' [pretty74.74193((3420,2470))]
component '74244' missing from library '6' [pretty74.74244((3420,2670))]
component '74138' missing from library '6' [pretty74.74138((3420,310))]
component '74238' missing from library '6' [pretty74.74238((3420,500))]
component '74573' missing from library '6' [pretty74.74573((3420,690))]
component '74688' missing from library '6' [pretty74.74688((360,1380))]
component '74682' missing from library '6' [pretty74.74682((360,1610))]
component '74682' missing from library '6' [pretty74.74682((360,1830))]
component '74688' missing from library '6' [pretty74.74688((360,2050))]
component '74688' missing from library '6' [pretty74.74688((360,2270))]
component '74688' missing from library '6' [pretty74.74688((360,2490))]
component '74238' missing from library '6' [pretty74.74238((360,3450))]
component '74688' missing from library '6' [pretty74.74688((700,1060))]
component '74688' missing from library '6' [pretty74.74688((700,1310))]
component '74688' missing from library '6' [pretty74.74688((700,1610))]
component '74688' missing from library '6' [pretty74.74688((700,310))]
component '74688' missing from library '6' [pretty74.74688((700,560))]
component '74688' missing from library '6' [pretty74.74688((700,810))]
component '74151' missing from library '6' [deleteme.74151((1040,1130))]
component '74573' missing from library '6' [deleteme.74573((1040,1330))]
component '74573' missing from library '6' [deleteme.74573((1040,1610))]
component '74573' missing from library '6' [deleteme.74573((1040,1850))]
component '74573' missing from library '6' [deleteme.74573((1040,2090))]
component '74573' missing from library '6' [deleteme.74573((1040,2330))]
component '74573' missing from library '6' [deleteme.74573((1040,2920))]
component '74573' missing from library '6' [deleteme.74573((1040,3160))]
component '74573' missing from library '6' [deleteme.74573((1040,3400))]
component '74573' missing from library '6' [deleteme.74573((1040,3640))]
component '74573' missing from library '6' [deleteme.74573((1040,3880))]
component '74279' missing from library '6' [deleteme.74279((1040,720))]
component '74279' missing from library '6' [deleteme.74279((1040,930))]
component '74374' missing from library '6' [deleteme.74374((2060,2920))]
component '74374' missing from library '6' [deleteme.74374((2060,3160))]
component '74138' missing from library '6' [deleteme.74138((2400,3720))]
component '74244' missing from library '6' [deleteme.74244((2400,3940))]
component '74244' missing from library '6' [deleteme.74244((2740,2910))]
component '74244' missing from library '6' [deleteme.74244((2740,3140))]
component '74244' missing from library '6' [deleteme.74244((2740,3750))]
component '74244' missing from library '6' [deleteme.74244((2740,3980))]
component '74244' missing from library '6' [deleteme.74244((3080,3970))]
component '74244' missing from library '6' [deleteme.74244((3410,3970))]
component '74688' missing from library '6' [deleteme.74688((360,1380))]
component '74682' missing from library '6' [deleteme.74682((360,1610))]
component '74682' missing from library '6' [deleteme.74682((360,1830))]
component '74688' missing from library '6' [deleteme.74688((360,2050))]
component '74688' missing from library '6' [deleteme.74688((360,2270))]
component '74688' missing from library '6' [deleteme.74688((360,2490))]
component '74688' missing from library '6' [deleteme.74688((700,1060))]
component '74688' missing from library '6' [deleteme.74688((700,1310))]
component '74688' missing from library '6' [deleteme.74688((700,1610))]
component '74688' missing from library '6' [deleteme.74688((700,310))]
component '74688' missing from library '6' [deleteme.74688((700,560))]
component '74688' missing from library '6' [deleteme.74688((700,810))]
Appearance element visible-ttl-register not found [alu74.visible-ttl-register]
Appearance element visible-ttl-register not found [alu74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [regs74.visible-ttl-register]
Appearance element visible-ttl-register not found [opc74.visible-ttl-register]
Appearance element visible-ttl-register not found [opc74.visible-ttl-register]
Appearance element visible-ttl-register not found [opc74.visible-ttl-register]
Appearance element visible-ttl-register not found [opc74.visible-ttl-register]
Appearance element visible-ttl-register not found [opc74.visible-ttl-register]
Appearance element visible-ttl-register not found [control74.visible-ttl-register]
Appearance element visible-ttl-register not found [control74.visible-ttl-register]
Appearance element visible-ttl-register not found [dev74.visible-ttl-register]
Appearance element visible-ttl-register not found [dev74.visible-ttl-register]

**Comment by jdah** [comment]
It actually isn't a library but just a fork of Logisim Evolution. You can get it here: https://github.com/jdah/logisim-evolution.

I'll note this in the README as well.
