### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by AwesomeKalin** [jdah/jdh-8#5]
Each question is on a new line
Would I be able to run a graphical app?
Would I be able to write an OS for this?

**Comment by Kylogias** [comment]
1. Graphical app? Probably, it is turing complete
2. Yes (I'm already planning on writing DOOM and a C-like compiler for it)

**Comment by jdah** [comment]
Yes and yes, as @Kylogias says it's Turing complete and it has support for arbitrary devices.
