### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by NeoGenio** [jdah/jdh-8#7]
A simple question. How do i run this? Because I have NO idea how to make it work.

**Comment by jdah** [comment]
Please read the README, if you can't get it running from there, please read about `make`.

**Comment by NeoGenio** [comment]
> Please read the README, if you can't get it running from there, please read about `make`.

I can get it to build but I can't start the emulator

**Comment by jdah** [comment]
See the files that get output under `./bin`

**Comment by NeoGenio** [comment]
Which files do I have to build using the assembler?
