### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by NeoGenio** [jdah/jdh-8#8]
How to use the emulator? I compile `pong.asm` using the assembler but when I type `./bin/emu out.bin` it says `Loading ROM from out.bin...` and nothing happens.

**Comment by jdah** [comment]
Please read the README. There's a `RUN` command which executes code starting from the current program counter location.

**Comment by NeoGenio** [comment]
I run but it says `Read/write attempt for non-present bank 0x0001` infinitely
