### ISSUE TITLE
Read/write attempt for non-present bank 0x0001

### ISSUE THREAD

**Issue by Nemesis300** [jdah/jdh-8#9]
I compile by running `./bin/asm programs/pong.asm` and it gives me a `out.bin` file. I emulate it by running `./bin/emu out.bin` and then typing `>RUN`. But it keeps saying `Read/write attempt for non-present bank 0x0001` infinitely

**Comment by jdah** [comment]
You need to run it with the modules `screen` and `kb`. You can do this either by using the `MOD` command in the emulator or by running the emulator with `--mod screen --mod kb`.

**Comment by NeoGenio** [comment]
> You need to run it with the modules `screen` and `kb`. You can do this either by using the `MOD` command in the emulator or by running the emulator with `--mod screen --mod kb`.

I type `RUN` and it starts, but it is very slow. Which speed should I input?

**Comment by Nemesis300** [comment]
> You need to run it with the modules `screen` and `kb`. You can do this either by using the `MOD` command in the emulator or by running the emulator with `--mod screen --mod kb`.

It starts but very slow. Which is the recommended speed I should input?

**Comment by jdah** [comment]
You can input your own argument to `RUN <hz>` as the number of `hz` you would like it to run at. IIRC it runs at 1 MHz in the video, but try out different speeds and see what works (could be different on your machine).
